CREATE DATABASE LOJADEBOLSAS;
USE LOJADEBOLSAS;

CREATE TABLE BOLSAS(
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PRECO DOUBLE,
  DESCONTO DOUBLE,
  QUANTIDADE_ESTOQUE INT,
  MARCA VARCHAR(50)
);

INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 250, 10, 100, 'COLCCI');
INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 500, 5, 10, 'PRADA');
INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 3500, 10, 107, 'ANACAPRI');
INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 200, 8, 100, 'FARM');
INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 300, 15, 1000, 'COLCCI');
INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 22000, 10, 1000, 'SANTA LOLLA');
INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 50000, 10, 1000, 'SANTA LOLLA');
INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 10000, 5, 300, 'ESTILE');
INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 1000, 15, 100, 'FARM');
INSERT INTO BOLSAS(PRECO, DESCONTO, QUANTIDADE_ESTOQUE, MARCA) VALUES ( 150, 10, 100, 'PRADA');


SELECT * FROM BOLSAS;

CREATE TABLE BOLSAS_CLIENTE(
 IDCLIENTE INTEGER,
 IDBOLSA INTEGER,
 FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(ID),
 FOREIGN KEY (IDBOLSA) REFERENCES BOLSAS(ID)
);

CREATE TABLE CLIENTE(
ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(70),
CPF VARCHAR(15) NOT NULL,
SENHA VARCHAR(8),
EMAIL VARCHAR(50),
TELEFONE VARCHAR(20)
);