/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dao.BolsasDAO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author suell
 */
public class TelaBolsas extends javax.swing.JFrame {

    /**
     * Creates new form TelaBolsas
     */
    public TelaBolsas() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnComprar2 = new javax.swing.JButton();
        btnComprar3 = new javax.swing.JButton();
        btnComprar4 = new javax.swing.JButton();
        btnComprar5 = new javax.swing.JButton();
        btnComprar1 = new javax.swing.JButton();
        btnComprar6 = new javax.swing.JButton();
        btnComprar7 = new javax.swing.JButton();
        btnComprar8 = new javax.swing.JButton();
        btnComprar9 = new javax.swing.JButton();
        btnComprar10 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ESCOLHA SUA BOLSA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 70, 300, 50);

        btnComprar2.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar2.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar2.setText("COMPRAR");
        btnComprar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar2);
        btnComprar2.setBounds(457, 580, 100, 22);

        btnComprar3.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar3.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar3.setText("COMPRAR");
        btnComprar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar3);
        btnComprar3.setBounds(887, 580, 90, 22);

        btnComprar4.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar4.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar4.setText("COMPRAR");
        btnComprar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar4);
        btnComprar4.setBounds(1077, 580, 100, 22);

        btnComprar5.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar5.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar5.setText("COMPRAR");
        btnComprar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar5);
        btnComprar5.setBounds(687, 580, 100, 22);

        btnComprar1.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar1.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar1.setText("COMPRAR");
        btnComprar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar1);
        btnComprar1.setBounds(220, 580, 100, 22);

        btnComprar6.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar6.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar6.setText("COMPRAR");
        btnComprar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar6);
        btnComprar6.setBounds(1047, 320, 100, 22);

        btnComprar7.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar7.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar7.setText("COMPRAR");
        btnComprar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar7);
        btnComprar7.setBounds(597, 320, 100, 22);

        btnComprar8.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar8.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar8.setText("COMPRAR");
        btnComprar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar8);
        btnComprar8.setBounds(220, 320, 100, 22);

        btnComprar9.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar9.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar9.setText("COMPRAR");
        btnComprar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar9);
        btnComprar9.setBounds(387, 320, 100, 22);

        btnComprar10.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar10.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar10.setText("COMPRAR");
        btnComprar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar10);
        btnComprar10.setBounds(817, 320, 100, 22);

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(1130, 20, 72, 22);

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir.setText("EXCLUIR CONTA");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(985, 20, 130, 22);

        btnConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("ATUALIZAR CONTA");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(810, 20, 150, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/Imagens/TelaBolsas.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 70, 1116, 582);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar7ActionPerformed
        // TODO add your handling code here:
        TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
    }//GEN-LAST:event_btnComprar7ActionPerformed

    private void btnComprar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar2ActionPerformed
        // TODO add your handling code here:
        TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
    }//GEN-LAST:event_btnComprar2ActionPerformed

    private void btnComprar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar8ActionPerformed
        // TODO add your handling code here:
        TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
        
    }//GEN-LAST:event_btnComprar8ActionPerformed

    private void btnComprar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar9ActionPerformed
        // TODO add your handling code here:
        TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
    }//GEN-LAST:event_btnComprar9ActionPerformed

    private void btnComprar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar10ActionPerformed
        // TODO add your handling code here:
        TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
    }//GEN-LAST:event_btnComprar10ActionPerformed

    private void btnComprar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar6ActionPerformed
        // TODO add your handling code here:
        TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
        

    }//GEN-LAST:event_btnComprar6ActionPerformed

    private void btnComprar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar4ActionPerformed
        // TODO add your handling code here:
        TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
    }//GEN-LAST:event_btnComprar4ActionPerformed

    private void btnComprar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar3ActionPerformed
        // TODO add your handling code here:
        TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
    }//GEN-LAST:event_btnComprar3ActionPerformed

    private void btnComprar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar5ActionPerformed
        // TODO add your handling code here:
       TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
    }//GEN-LAST:event_btnComprar5ActionPerformed

    private void btnComprar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar1ActionPerformed
        // TODO add your handling code here:
        TelaFinalizarCompra finalizarcompra = new TelaFinalizarCompra();
        finalizarcompra.setVisible(true);
    }//GEN-LAST:event_btnComprar1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        TelaExcluir telaexcluir = new TelaExcluir();
        telaexcluir.setVisible(true);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        TelaAtualizar telaatualizar = new TelaAtualizar();
        telaatualizar.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBolsas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar1;
    private javax.swing.JButton btnComprar10;
    private javax.swing.JButton btnComprar2;
    private javax.swing.JButton btnComprar3;
    private javax.swing.JButton btnComprar4;
    private javax.swing.JButton btnComprar5;
    private javax.swing.JButton btnComprar6;
    private javax.swing.JButton btnComprar7;
    private javax.swing.JButton btnComprar8;
    private javax.swing.JButton btnComprar9;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
