/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author suell
 */
public class TelaFinalizarCompra extends javax.swing.JFrame {

    /**
     * Creates new form TelaFinalizarCompra
     */
    public TelaFinalizarCompra() {
        initComponents();
        GrupoBotoes.add(radioCredito);
        GrupoBotoes.add(radioDebito);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotoes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNumCartao = new javax.swing.JTextField();
        txtNomeCartao = new javax.swing.JTextField();
        txtCVV = new javax.swing.JTextField();
        txtValidade = new javax.swing.JFormattedTextField();
        radioDebito = new javax.swing.JRadioButton();
        radioCredito = new javax.swing.JRadioButton();
        btnFinalizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INSIRA SEU ENDEREÇO E O MÉTODO DE PAGAMENTO PARA FINALIZAR A COMPRA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 50, 443, 30);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ESTADO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(950, 200, 140, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CIDADE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(950, 270, 80, 16);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CEP");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(950, 340, 60, 16);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("BAIRRO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(950, 400, 90, 16);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ENDEREÇO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(940, 130, 150, 16);

        txtBairro.setBackground(new java.awt.Color(255, 255, 255));
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        getContentPane().add(txtBairro);
        txtBairro.setBounds(950, 420, 190, 22);

        txtCEP.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCEP);
        txtCEP.setBounds(950, 360, 200, 22);

        txtCidade.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCidade);
        txtCidade.setBounds(950, 290, 200, 22);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Aqui", "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(950, 222, 200, 20);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("N° DO CARTÃO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(690, 200, 110, 20);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("NOME NO CARTÃO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(690, 270, 150, 16);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CVV");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(690, 330, 60, 20);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("VALIDADE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(690, 400, 90, 16);

        txtNumCartao.setBackground(new java.awt.Color(255, 255, 255));
        txtNumCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCartaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumCartao);
        txtNumCartao.setBounds(690, 220, 200, 22);

        txtNomeCartao.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNomeCartao);
        txtNomeCartao.setBounds(690, 290, 200, 22);

        txtCVV.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCVV);
        txtCVV.setBounds(690, 350, 200, 22);

        txtValidade.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtValidade);
        txtValidade.setBounds(690, 420, 200, 22);

        radioDebito.setText("DÉBITO");
        radioDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDebitoActionPerformed(evt);
            }
        });
        getContentPane().add(radioDebito);
        radioDebito.setBounds(800, 170, 80, 20);

        radioCredito.setText("CRÉDITO");
        getContentPane().add(radioCredito);
        radioCredito.setBounds(690, 170, 80, 20);

        btnFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizar.setText("FINALIZAR COMPRA");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar);
        btnFinalizar.setBounds(840, 500, 160, 30);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("PAGAMENTO");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(700, 130, 80, 16);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/Imagens/login (1).jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-60, -30, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValidadeActionPerformed

    private void radioDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDebitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDebitoActionPerformed

    private void txtNumCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCartaoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bolsa Comprada.");
        TelaBolsas telabolsas = new TelaBolsas();
        telabolsas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinalizarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotoes;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioCredito;
    private javax.swing.JRadioButton radioDebito;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtNomeCartao;
    private javax.swing.JTextField txtNumCartao;
    private javax.swing.JFormattedTextField txtValidade;
    // End of variables declaration//GEN-END:variables
}
